// src/styles/theme.ts
export const theme = {
	colors: {
		primary: '#2DBA4F',
		secondary: '#FF8E00',
		accent: '#3348A4',
		greyScale: {
			offWhite: '#FAFCFE',
			frenchGray: '#C9C9C9',
			dimGray: '#808080',
			eerieBlack: '#15181B',
			strokeWhite: '#C7C7C7',
			onyx: '#323538',
		},
		semanticColors: {
			background_1: '#F7F7F7',
			background_2: '#EDEDED',
			footer: '#212121',
			danger: {
				danger: '#BA2D2F',
				dangerBackground: '#E6B3B4',
				dangerHover: '#9C2627',
			},
			warn: {
				warn: '#F6BE24',
				warnBackground: '#FCE8B0',
				warnHover: '#CFA01E',
			},
			sucess: {
				sucess: '#1D7C4D',
				sucessBackground: '#E2F9ED',
				sucessHover: '#30AB6F',
			},
			info: {
				info: '#3062D4',
				infoBackground: '#DDE7FF',
				infoHover: '#4D78DB',
			},
		},
		gradientPrimary: {
			gradient_50: '#C4ECCE',
			gradient_100: '#B3E6C0',
			gradient_200: '#92DBA3',
			gradient_300: '#70D087',
			gradient_400: '#4FC56B',
			gradient_600: '#269C42',
			gradient_700: '#1F7E36',
			gradient_800: '#176129',
			gradient_900: '#10431C',
		},
		gradientSecondary: {
			gradient_50: '#FFDFB8',
			gradient_100: '#FFD6A3',
			gradient_200: '#FFC47A',
			gradient_300: '#FFB252',
			gradient_400: '#FFA029',
			gradient_600: '#D67700',
			gradient_700: '#AD6100',
			gradient_800: '#854A00',
			gradient_900: '#5C3300',
		},
		gradientAccent: {
			gradient_50: '#C6CCE6',
			gradient_100: '#B6BDDE',
			gradient_200: '#95A0D0',
			gradient_300: '#7483C1',
			gradient_400: '#5465B3',
			gradient_600: '#2B3C8A',
			gradient_700: '#233170',
			gradient_800: '#1B2555',
			gradient_900: '#121A3B',
		},
	},
	fonts: {
		hind: {
			bold: 'Hind-Bold',
			light: 'Hind-Light',
			medium: 'Hind-Medium',
			regular: 'Hind-Regular',
			semiBold: 'Hind-SemiBold',
		},
		lora: {
			bold: 'Lora-Bold',
			boldItalic: 'Lora-BoldItalic',
			italic: 'Lora-Italic',
			medium: 'Lora-Medium',
			mediumItalic: 'Lora-MediumItalic',
			regular: 'Lora-Regular',
			semiBold: 'Lora-SemiBold',
			semiBoldItalic: 'Lora-SemiBoldItalic',
		},
		montserrat: {
			black: 'Montserrat-Black',
			blackItalic: 'Montserrat-BlackItalic',
			bold: 'Montserrat-Bold',
			boldItalic: 'Montserrat-BoldItalic',
			extraBold: 'Montserrat-ExtraBold',
			extraBoldItalic: 'Montserrat-ExtraBoldItalic',
			extraLight: 'Montserrat-ExtraLight',
			extraLightItalic: 'Montserrat-ExtraLightItalic',
			italic: 'Montserrat-Italic',
			light: 'Montserrat-Light',
			lightItalic: 'Montserrat-LightItalic',
			medium: 'Montserrat-Medium',
			mediumItalic: 'Montserrat-MediumItalic',
			regular: 'Montserrat-Regular',
			semiBold: 'Montserrat-SemiBold',
			semiBoldItalic: 'Montserrat-SemiBoldItalic',
			thin: 'Montserrat-Thin',
			thinItalic: 'Montserrat-ThinItalic',
		},
	},
}
